Repository WordPress/twentytwentyfive, pull requests merged in 2024-10, with the labels that each got.

#483 Landing page patterns: Replace level 1 headings (H1)
  patterns/cta-centered-heading.php
  patterns/event-rsvp.php
  patterns/page-coming-soon.php
  patterns/page-portfolio-home.php
Labels: [Type] Bug

#487 Remove the more posts pattern from the default archive template
  templates/archive.html
Labels: [Type] Bug

#488 Remove the "media" category from two patterns
  patterns/event-schedule.php
  patterns/grid-with-categories.php
Labels: [Type] Enhancement

#482 Backport comment formatting change
  functions.php
Labels: [Type] Bug

#494 Add links to post dates
  patterns/hidden-sidebar.php
  patterns/template-home-posts-grid-news-blog.php
  patterns/template-home-with-sidebar-news-blog.php
  patterns/template-query-loop-news-blog.php
  patterns/template-query-loop-vertical-header-blog.php
Labels: [Type] Bug

#496 Multiple templates: Fix underline inconsistencies
  patterns/hidden-written-by.php
  patterns/post-with-left-aligned-content.php
  patterns/template-single-news-blog.php
  patterns/template-single-vertical-header-blog.php
  theme.json
Labels: Accessibility (a11y), [Status] Needs Design Feedback

#505 Requires PHP: remove patch version
  readme.txt
  style.css
Labels: [Type] Enhancement

#507 Evening, section style 3: update link color to maintain contrast ratio
  styles/01-evening.json
  styles/colors/01-evening.json
Labels: [Type] Bug

#508 Add missing ARIA landmark roles
  patterns/cta-newsletter.php
  patterns/template-single-vertical-header-blog.php
Labels: [Type] Bug, Accessibility (a11y)

#510 Fix/banner book desc heading
  patterns/banner-about-book.php
Labels: [Type] Bug, Accessibility (a11y)

#523 Fix: Update `Accent 1` color for Midnight variation.
  styles/08-midnight.json
  styles/colors/08-midnight.json
Labels: [Type] Bug

#521 Fix: Color problems with "CV/bio" pattern
  patterns/page-cv-bio.php
Labels: [Type] Bug, Accessibility (a11y), [Component] Block Patterns

#522 Fix: Color problems with "CTA with grid layout with products and link"
  patterns/cta-grid-products-link.php
Labels: [Type] Bug, Accessibility (a11y), [Component] Block Patterns

#530 Fix: Replace empty paragraph with spacer.
  patterns/page-link-in-bio-heading-paragraph-links-image.php
  patterns/page-link-in-bio-with-tight-margins.php
Labels: [Type] Bug

#520 Fix: Remove redundant `fontStyle` and `fontWeight`
  styles/02-noon.json
  styles/03-dusk.json
  styles/04-afternoon.json
  styles/05-twilight.json
  styles/08-midnight.json
  styles/typography/typography-preset-1.json
  styles/typography/typography-preset-2.json
  styles/typography/typography-preset-3.json
  styles/typography/typography-preset-4.json
  styles/typography/typography-preset-7.json
  theme.json
Labels: [Type] Bug, [Component] theme.json, [Component] Style Variations

#532 Try: Clean up posts patterns
  patterns/page-business-home.php
  patterns/page-shop-home.php
  patterns/template-query-loop-photo-blog.php
Labels: [Type] Bug

#535 Update submenu and overlay color of the header navigation
  patterns/header-centered.php
  patterns/header-columns.php
  patterns/header-large-title.php
  patterns/header.php
  patterns/vertical-header.php
Labels: [Type] Enhancement

#544 List block: polish spacing between indented items
  theme.json
Labels: [Type] Bug

#539 Try: Audit featured patterns.
  patterns/banner-about-book.php
  patterns/banner-intro-image.php
  patterns/banner-intro.php
  patterns/banner-poster.php
  patterns/cta-book-links.php
  patterns/cta-book-locations.php
  patterns/cta-centered-heading.php
  patterns/cta-grid-products-link.php
  patterns/event-3-col.php
  patterns/event-schedule.php
  patterns/format-audio.php
  patterns/format-link.php
  patterns/grid-videos.php
  patterns/grid-with-categories.php
  patterns/hero-book.php
  patterns/hero-full-width-image.php
  patterns/hero-overlapped-book-cover-with-links.php
  patterns/hero-podcast.php
  patterns/logos.php
  patterns/overlapped-images.php
  patterns/page-cv-bio.php
  patterns/page-link-in-bio-with-tight-margins.php
  patterns/page-portfolio-home.php
  patterns/page-shop-home.php
  patterns/pricing-2-col.php
  patterns/pricing-3-col.php
  patterns/services-3-col.php
  patterns/services-subscriber-only-section.php
  patterns/text-faqs.php
Labels: [Type] Enhancement

#528 Fix: Color problems with the newsletter sign-up pattern
  patterns/cta-newsletter.php
Labels: [Type] Bug, Accessibility (a11y), [Component] Block Patterns

#543 Update/pattern headings
  patterns/banner-cover-big-heading.php
  patterns/page-cv-bio.php
Labels: [Type] Enhancement

#550 Try: Update instagram grid pattern to use the group (option 1)
  patterns/media-instagram-grid.php
Labels: [Type] Enhancement, [Component] Block Patterns

#554 update: tag line height
  styles/blocks/post-terms-1.json
Labels: [Type] Enhancement

#556 Afternoon: Update button colors
  styles/04-afternoon.json
  styles/colors/04-afternoon.json
Labels: [Type] Enhancement, Accessibility (a11y)

#559 Try: Remove link color in "Link format" pattern.
  patterns/format-link.php
Labels: [Type] Enhancement

#536 Try: Remove images to reduce zip size.
  assets/images/avatar.webp
  assets/images/hero-podcast.webp
  assets/images/image-from-rawpixel-id-13029755.webp
  assets/images/image-from-rawpixel-id-8803077-original.webp
  assets/images/location.webp
  patterns/heading-and-paragraph-with-image.php
  patterns/testimonials-2-col.php
  readme.txt
Labels: [Type] Enhancement

#514 Full page patterns: Improve zoom out
  patterns/page-business-home.php
  patterns/page-landing-book.php
  patterns/page-landing-event.php
  patterns/page-landing-podcast.php
  patterns/page-portfolio-home.php
  patterns/page-shop-home.php
Labels: [Type] Enhancement, [Component] Block Patterns, [Priority] High

#569 Link in bio with profile: Update color of the social icons
  patterns/page-link-in-bio-wide-margins.php
Labels: [Type] Bug

#568 Morning: Update the color contrast on the button in section style 4
  styles/06-morning.json
Labels: [Type] Bug

#561 Try: Update morning & typography preset 5
  styles/06-morning.json
  styles/colors/06-morning.json
  styles/typography/typography-preset-5.json
Labels: [Type] Enhancement, [Component] Style Variations

#563 Try: Update midnight & typography preset 7.
  styles/08-midnight.json
  styles/typography/typography-preset-7.json
Labels: [Type] Enhancement, [Component] Style Variations

#567 Photo single post: Update post content settings
  patterns/template-single-photo-blog.php
Labels: [Type] Bug

#577 News blog with featured posts grid: Replace footer
  parts/footer-columns.html
  patterns/template-home-posts-grid-news-blog.php
  theme.json
Labels: [Type] Bug

#573 Alternative to "Hero, overlapped book cover with links" without split background
  patterns/hero-overlapped-book-cover-with-links.php
Labels: [Type] Enhancement, [Component] Block Patterns

#575 Update the viewport width of the vertical header
  patterns/vertical-header.php
Labels: [Type] Enhancement

#537 Try: Escape apostrophe in translation functions.
  patterns/banner-about-book.php
  patterns/banner-poster.php
  patterns/cta-events-list.php
  patterns/event-rsvp.php
  patterns/event-schedule.php
  patterns/page-cv-bio.php
  patterns/page-link-in-bio-wide-margins.php
  patterns/page-link-in-bio-with-tight-margins.php
  patterns/testimonials-2-col.php
  patterns/testimonials-6-col.php
  patterns/testimonials-large.php
Labels: [Type] Enhancement, Internationalization (i18n)

#581 Try: Fix display of the annotation.
  styles/blocks/03-annotation.json
Labels: [Type] Enhancement

#596 Update preview action.
  .github/workflows/preview.yml
Labels: [Type] Enhancement, Task

#594 Change/image names
  README.md
  assets/images/404-image.webp
  assets/images/akaka-falls-state-park-flora.webp
  assets/images/botany-flowers-closeup.webp
  assets/images/campanula-alliariifolia-flower.webp
  assets/images/delphinium-flowers.webp
  assets/images/malibu-plantlife.webp
  assets/images/northern-buttercups-flowers.webp
  assets/images/red-hibiscus-closeup.webp
  assets/images/ruins-image.webp
  assets/images/star-thristle-flower.webp
  patterns/cta-grid-products-link.php
  patterns/event-3-col.php
  patterns/event-rsvp.php
  patterns/format-audio.php
  patterns/heading-and-paragraph-with-image.php
  patterns/hero-full-width-image.php
  patterns/hidden-404.php
  patterns/overlapped-images.php
  patterns/services-3-col.php
  readme.txt
Labels: [Type] Enhancement

#599 Fix: Remove metadata.
  patterns/format-audio.php
  patterns/format-link.php
Labels: [Type] Enhancement

#600 Update: Set correct footers and header to "News" blog templates
  parts/header-large-title.html
  patterns/template-archive-news-blog.php
  patterns/template-home-news-blog.php
  patterns/template-home-posts-grid-news-blog.php
  patterns/template-home-with-sidebar-news-blog.php
  patterns/template-single-left-aligned-content.php
  patterns/template-single-news-blog.php
  theme.json
Labels: [Type] Enhancement

#607 Try: Reduce image size.
  assets/images/404-image.webp
  assets/images/grid-flower-2.webp
  assets/images/link-in-bio-image.webp
  assets/images/poster-image-background.webp
  assets/images/ruins-image.webp
Labels: [Type] Enhancement

#608 Try: Post format binding.
  functions.php
  patterns/binding-format.php
Labels: [Type] Enhancement

#614 Sunrise & preset 6: Remove font size from author name
  styles/07-sunrise.json
  styles/typography/typography-preset-6.json
Labels: [Type] Enhancement

#617 Fix: Poster-like date text
  patterns/banner-poster.php
Labels: [Type] Bug, [Component] Block Patterns

#624 Fix: Rebuild Event RSVP Pattern.
  patterns/event-rsvp.php
Labels: [Type] Enhancement

#623 Add translator note for multilingual strings.
  patterns/banner-poster.php
  patterns/cta-events-list.php
  patterns/event-rsvp.php
Labels: [Type] Enhancement, Internationalization (i18n)

#635 Fix: Parity between style variations and colors + typography presets.
  styles/colors/06-morning.json
  styles/colors/08-midnight.json
  styles/typography/typography-preset-3.json
  styles/typography/typography-preset-6.json
  styles/typography/typography-preset-7.json
Labels: [Type] Bug

#650 Twilight, Section 5: Adjust the border color for search input
  styles/05-twilight.json
Labels: [Type] Bug

#656 Remove text color from the term description block
  theme.json
Labels: [Type] Bug

#646 Alt: FAQs: Replace Details blocks with headings and separators.
  patterns/text-faqs.php
Labels: Internationalization (i18n)

#660 Fix: Rename "Post format" category to "Post formats"
  functions.php
Labels: [Type] Bug, Internationalization (i18n)

#632 Translations: edits for capitalization and consistency
  patterns/cta-heading-search.php
  patterns/event-schedule.php
  patterns/footer-centered.php
  patterns/footer-columns.php
  patterns/footer-newsletter.php
  patterns/footer-social.php
  patterns/footer.php
  patterns/hero-podcast.php
  patterns/hidden-search.php
  patterns/media-instagram-grid.php
  patterns/services-subscriber-only-section.php
  patterns/template-home-with-sidebar-news-blog.php
  patterns/template-query-loop-vertical-header-blog.php
  patterns/template-query-loop.php
Labels: Internationalization (i18n)
